BudgetWepApp/Models/Goal.cs
using System.ComponentModel.DataAnnotations;

namespace BudgetWepApp.Models
{
    public class Goal
    {
        public int? GoalID { get; set; }
        public string? userId { get; set; }
        public User? User { get; set; }
        [Required(ErrorMessage = "A name for your goal is required.")]
        public string Name { get; set; }
        [Required(ErrorMessage = "A description of your goal is required.")]
        public string Description { get; set; }
        public DateTime DateAddded { get; set; }
        public bool IsCompleted { get; set; }
    }
}

BudgetWepApp/Controllers/BankAccountController.cs
using BudgetWepApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace BudgetWepApp.Controllers
{
    public class BankAccountController : Controller
    {
        private IUserContext context;
        private readonly UserManager<User> userManager;
        public BankAccountController(IUserContext ctx, UserManager<User> userManager)
        {
            context = ctx;
            this.userManager = userManager;
        }
        [Authorize]
        [HttpGet]
        public IActionResult BankAccountInfo(UserViewModel model)
        {
            var theme = Request.Cookies["data-bs-theme"];
            ViewBag.Theme = theme;
            CookieOptions cookies = new CookieOptions
            {
                Expires = DateTime.Now.AddDays(60)
            };
            //this will be got from session later

            string userID = userManager.GetUserId(User);
            //Populates the model
            model.User = context.Users.FirstOrDefault(u => u.Id == userID);

            if (model.User == null)
            {
                return NotFound("User not found");
            }

            model.Goals = context.Goals.Where(g => g.User.Id == userID).ToList();
            model.Income = context.Incomes.Where(i => i.User.Id == userID).ToList();
            model.RecurringPayments = context.recurringPayments.Where(r => r.User.Id == userID).ToList();
            model.Transactions = context.Transactions.Where(t => t.User.Id == userID).OrderByDescending(t => t.TransactionID).ToList();

            return View(model);
        }

        [HttpPost]
        public IActionResult AddIncome(NewTransationViewModel model)
        {
            if (ModelState.IsValid)
            {
                var theme = Request.Cookies["data-bs-theme"];
                ViewBag.Theme = theme;
                CookieOptions cookies = new CookieOptions
                {
                    Expires = DateTime.Now.AddDays(60)
                };

                string userID = userManager.GetUserId(User);
                User user = context.Users.FirstOrDefault(u => u.Id == userID);


                if (user == null)
                {
                    return NotFound("User not found");
                }

                if (model.Amount <= 0)
                {
                    return BadRequest("Number not positive");
                }

                if (model.FrequencyInDays > 0)
                {
                    var newIncome = new Income()
                    {
                        User = user,
                        IncomeAmmount = model.Amount,
                        PayPeriodDays = model.FrequencyInDays ?? 0,
                        StartingDate = DateTime.Now,
                    };

                    context.Incomes.Add(newIncome);
                }

                if (model.UpdateTransactions)
                {
                    var newTransaction = new Transaction()
                    {
                        User = user,
                        TimeStamp = DateTime.Now,
                        Ammount = model.Amount
                    };

                    context.Transactions.Add(newTransaction);

                    user.CurrentBalance += model.Amount;
                }

                context.SaveChanges();

                return RedirectToAction("BankAccountInfo");
            }

            return View("BankAccountInfo");
        }

        [HttpPost]
        public IActionResult RemoveIncome(int incomeId)
        {
            var theme = Request.Cookies["data-bs-theme"];
            ViewBag.Theme = theme;
            CookieOptions cookies = new CookieOptions
            {
                Expires = DateTime.Now.AddDays(60)
            };
            var income = context.Incomes.FirstOrDefault(i => i.IncomeID == incomeId);

            if (income != null)
            {
                context.Incomes.Remove(income);
                context.SaveChanges();
            }

            return RedirectToAction("BankAccountInfo");
        }

    }
}

BudgetWepApp/Controllers/GoalController.cs
using BudgetWepApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace BudgetWepApp.Controllers
{
    public class GoalController : Controller
    {
        private IUserContext context;
        private readonly UserManager<User> userManager;
        public GoalController(IUserContext ctx, UserManager<User> userManager)
        {
            context = ctx;
            this.userManager = userManager;
        }
        [Authorize]
        public IActionResult Goals()
        {
            var theme = Request.Cookies["data-bs-theme"];
            ViewBag.Theme = theme;
            CookieOptions cookies = new CookieOptions
            {
                Expires = DateTime.Now.AddDays(60)
            };
            string userID = userManager.GetUserId(User);
            var goals = context.Goals.Where(g => g.userId == userID).ToList() ?? new List<Goal>();
            return View(goals);
        }

        [Authorize]
        public IActionResult CreateGoal()
        {
            var theme = Request.Cookies["data-bs-theme"];
            ViewBag.Theme = theme;
            CookieOptions cookies = new CookieOptions
            {
                Expires = DateTime.Now.AddDays(60)
            };
            return View();
        }

        [HttpPost]
        public IActionResult CreateGoal(Goal goal)
        {
            var theme = Request.Cookies["data-bs-theme"];
            ViewBag.Theme = theme;
            CookieOptions cookies = new CookieOptions
            {
                Expires = DateTime.Now.AddDays(60)
            };
            string userID = userManager.GetUserId(User);

            goal.User = context.Users.FirstOrDefault(u => u.Id == userID);

            if (goal.User == null)
            {
                ModelState.AddModelError("", "User not found.");
            }
            if (ModelState.IsValid) 
            { 
                goal.DateAddded = DateTime.Now;
                context.Goals.Add(goal);
                context.SaveChanges();
                return RedirectToAction("Goals", new { userId = goal.userId });
            } else
            {
                return View(goal);
            }
           }
        [Authorize]
        [HttpGet]
        public IActionResult GoalDetails(int goalId)
        {
            var theme = Request.Cookies["data-bs-theme"];
            ViewBag.Theme = theme;
            CookieOptions cookies = new CookieOptions
            {
                Expires = DateTime.Now.AddDays(60)
            };
            var goal = context.Goals.FirstOrDefault(g => g.GoalID == goalId);
            if (goal == null)
            {
                return NotFound("Goal not found");
            }
            return View(goal);
        }
        [Authorize]
        [HttpGet]
        public IActionResult EditGoal(int goalId)
        {
            var theme = Request.Cookies["data-bs-theme"];
            ViewBag.Theme = theme;
            CookieOptions cookies = new CookieOptions
            {
                Expires = DateTime.Now.AddDays(60)
            };
            var goal = context.Goals.FirstOrDefault(g => g.GoalID == goalId);
            if (goal == null)
            {
                return NotFound("Goal not found");
            }
            return View(goal);
        }
        [HttpPost]
        public IActionResult EditGoal(Goal goal)
        {
            var theme = Request.Cookies["data-bs-theme"];
            ViewBag.Theme = theme;
            CookieOptions cookies = new CookieOptions
            {
                Expires = DateTime.Now.AddDays(60)
            };
            if (ModelState.IsValid)
            {
                var goalToUpdate = context.Goals.FirstOrDefault(g => g.GoalID == goal.GoalID);
                if (goalToUpdate != null)
                {
                    goalToUpdate.Name = goal.Name;
                    goalToUpdate.Description = goal.Description;
                    goalToUpdate.DateAddded = DateTime.Now;
                    context.SaveChanges();
                    return RedirectToAction("Goals", new { userId = goalToUpdate.userId });
                }
                else
                {
                    return NotFound("Goal not found");
                }
            }
            return View(goal);
        }
        [Authorize]
        [HttpGet]
        public IActionResult DeleteGoal(int goalId)
        {
            var theme = Request.Cookies["data-bs-theme"];
            ViewBag.Theme = theme;
            CookieOptions cookies = new CookieOptions
            {
                Expires = DateTime.Now.AddDays(60)
            };
            var goal = context.Goals.FirstOrDefault(g => g.GoalID == goalId);
            if (goal == null)
            {
                return NotFound("Goal not found");
            }
            return View(goal);
        }
        [HttpPost]
        public IActionResult ConfirmDelete(int goalId)
        {
            var theme = Request.Cookies["data-bs-theme"];
            ViewBag.Theme = theme;
            CookieOptions cookies = new CookieOptions
            {
                Expires = DateTime.Now.AddDays(60)
            };
            var goal = context.Goals.FirstOrDefault(g => g.GoalID == goalId);

            if (goal != null)
            {
                context.Goals.Remove(goal);
                context.SaveChanges();
            }

            return RedirectToAction("Goals");
        }
        [HttpPost]
        public IActionResult UpdateCompletedGoal(int GoalID, bool Completed)
        {
            var theme = Request.Cookies["data-bs-theme"];
            ViewBag.Theme = theme;
            CookieOptions cookies = new CookieOptions
            {
                Expires = DateTime.Now.AddDays(60)
            };
            var goal = context.Goals.FirstOrDefault(g => g.GoalID == GoalID);
            if (goal == null)
            {
                return NotFound();
            }
            goal.IsCompleted = Completed;
            context.SaveChanges();
            return RedirectToAction("Goals", new { goalId = GoalID });
        }
    }
}

BudgetWepApp/Controllers/WithdrawalsController.cs
using BudgetWepApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace BudgetWepApp.Controllers
{
    public class WithdrawalsController : Controller
    {
        private IUserContext context;
        private readonly UserManager<User> userManager;
        public WithdrawalsController(IUserContext ctx, UserManager<User> userManager)
        {
            context = ctx;
            this.userManager = userManager;
        }

        [Authorize]
        public IActionResult WithdrawalsPage(UserViewModel model)
        {
            var theme = Request.Cookies["data-bs-theme"];
            ViewBag.Theme = theme;
            CookieOptions cookies = new CookieOptions
            {
                Expires = DateTime.Now.AddDays(60)
            };
            //this will be got from session later
            string userID = userManager.GetUserId(User);

            //Populates the model
            model.User = context.Users.FirstOrDefault(u => u.Id == userID);

            if (model.User == null)
            {
                return NotFound("User not found");
            }

            model.Goals = context.Goals.Where(g => g.User.Id == userID).ToList();
            model.Income = context.Incomes.Where(i => i.User.Id == userID).ToList();
            model.RecurringPayments = context.recurringPayments.Where(r => r.User.Id == userID).ToList();
            model.Transactions = context.Transactions.Where(t => t.User.Id == userID).OrderByDescending(t => t.TransactionID).ToList();

            return View(model);
        }

        [HttpPost]
        public IActionResult AddPayment(NewTransationViewModel model)
        {
            if (ModelState.IsValid)
            {
                var theme = Request.Cookies["data-bs-theme"];
                ViewBag.Theme = theme;
                CookieOptions cookies = new CookieOptions
                {
                    Expires = DateTime.Now.AddDays(60)
                };
                string userID = userManager.GetUserId(User);
                User user = context.Users.FirstOrDefault(u => u.Id == userID);

                if (user == null)
                {
                    return NotFound("User not found");
                }

                if (model.Amount <= 0)
                {
                    return BadRequest("Number not positive");
                }

                if (model.FrequencyInDays > 0)
                {
                    var newPayment = new RecurringPayment()
                    {
                        User = user,
                        PaymentAmount = model.Amount,
                        PaymenFrequencyDays = model.FrequencyInDays ?? 0,
                        StartingDate = DateTime.Now,
                    };

                    context.recurringPayments.Add(newPayment);
                }

                if (model.UpdateTransactions)
                {
                    var newTransaction = new Transaction()
                    {
                        User = user,
                        TimeStamp = DateTime.Now,
                        Ammount = model.Amount * -1
                    };

                    context.Transactions.Add(newTransaction);

                    user.CurrentBalance -= model.Amount;
                }

                context.SaveChanges();

                return RedirectToAction("WithdrawalsPage");
            }

            return View("WithdrawalsPage");
        }

        [HttpPost]
        public IActionResult RemovePayment(int paymentId)
        {
            var theme = Request.Cookies["data-bs-theme"];
            ViewBag.Theme = theme;
            CookieOptions cookies = new CookieOptions
            {
                Expires = DateTime.Now.AddDays(60)
            };
            var payment = context.recurringPayments.FirstOrDefault(p => p.RecurringPaymentId == paymentId);

            if (payment != null)
            {
                context.recurringPayments.Remove(payment);
                context.SaveChanges();
            }

            return RedirectToAction("WithdrawalsPage");
        }
    }
}

BudgetWepApp/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact Us";
}
<h1>@ViewData["Title"]</h1>
<form asp-action="Contact" method="post">
    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="form-group">
        <label>Full Name:</label>
        <input type="text" class="form-control" />
    </div>

    <div class="form-group">
        <label>Email:</label>
        <input type="email" class="form-control" />
    </div>
    <br />

    <div class="form-group">
        <label>What do you need help with?</label>
        <input type="radio" name="reasonOfContact" /> Financial Advice
        <input type="radio" name="reasonOfContact" /> Budgeting Advice
        <input type="radio" name="reasonOfContact" /> Website Help
    </div>
    <br />

    <div class="form-group">
        <label>Tell us what you are struggling with:</label>
        <p>
            <textarea name="addInfo" id="addInfo" rows="8" cols="64"></textarea>
        </p>
    </div>
    <br />

    <div class="form-group">
        <a asp-action="Thanks" asp-controller="Home" class="btn btn-primary">Submit</a>
        <button type="reset" value="Reset" class="btn btn-secondary">Reset</button>
    </div>
</form>

BudgetWepApp/Views/Home/Goals.cshtml
@model List<BudgetWepApp.Models.Goal>
@{
    ViewData["Title"] = "Goals";
}
<h1>@ViewData["Title"]</h1>
<h2>List of My Goals</h2>
@if (Model == null || !Model.Any())
{
    <p>No goals found.</p>
} else {
    <div class="goalCard">
        @foreach (var goal in Model)
        {
            <div class="card mb-3">
                <div class="card-body">
                    <a asp-controller="Home" asp-action="GoalDetails" asp-route-goalId="@goal.GoalID">
                        <h5 class="card-title @(goal.IsCompleted ? "text-success" : "")">@goal.Name</h5>
                    </a>
                    <p class="card-text">@goal.Description</p>
                    @if(goal.IsCompleted)
                    {
                        <p class="text-success fw-bold">Goal Completed</p>
                    }
                </div>
            </div>
            }
        </div>
        
}
<a asp-controller="Home" asp-action="CreateGoal" class="btn btn-primary mt-3">Add New Goal</a>

BudgetWepApp/Views/Home/Index.cshtml
@model UserViewModel
@using Microsoft.AspNetCore.Identity
@inject SignInManager<User> signInManager
@{
    ViewData["Title"] = "Home Page";
    var golTot = 0;
    double totalExpenses = 0;
    double totalIncome = 0;
}
@if (!signInManager.IsSignedIn(User))
{
    <div class="col">
        <h2 class="text-center">Please Log In</h2>
    </div>
}
else{
<div class="container px-4">
    <h2 class="text-center">Welcome</h2>
    <div class="container overflow-hidden">
    <div class="row gx-5">
                <div class="col">
                    <div class="p-3 border bg-light text-center">Current Balance</div>
                <div class="p-3 border bg-light">@Model.User.CurrentBalance.ToString("C2")</div>
                <div class="p-3 border bg-light">
                    <a class="btn btn-primary" asp-action="BankAccountInfo" asp-controller="BankAccount" style="display: flex; justify-content: center;">Bank Account Information</a>
                </div>
            </div>
            @foreach (Transaction transaction in Model.Transactions)
            {
                if(transaction == Model.Transactions.First()){
                <div class="col">
                    <div class="p-3 border bg-light text-center">Transactions</div>
                <div class="p-3 border bg-light">Last Transaction @transaction.Ammount.ToString("C2")</div>
                <div class="p-3 border bg-light">
                    <a class="btn btn-primary" asp-controller="Withdrawals"
                       asp-action="WithdrawalsPage" style="display: flex; justify-content: center;">
                        Transactions
                    </a>
                </div>
            </div>
                }
            }
            @foreach (Goal gol in Model.Goals)
            {
                 golTot = golTot + 1;
            }
            <div class="col">
                <div class="p-3 border bg-light text-center">My Goals</div>
                <div class="p-3 border bg-light">
                    <div class="goalCard">
                        @foreach (var goal in Model.Goals)
                        {
                            <div class="card mb-3">
                                <div class="card-body">
                                        <h5 class="card-title @(goal.IsCompleted ? "text-success" : "")"><vc:goal-link name="@goal.Name">@goal.Name</vc:goal-link></h5>
                                </div>
                            </div>
                        }
                    </div>
                    <!--<a class="btn btn-primary" asp-controller="Home"></a>-->
                   Total Goals: @golTot <a class="btn btn-primary" asp-controller="Goal" asp-action="Goals" style="display: flex; justify-content: center;"> Add Goals</a>
                </div>
            </div>
    </div>
    </div>
                <div class="container overflow-hidden" style="margin-top: 50px;">
                    <div class="row gx-5">
                <div class="col">
                    <div class="p-3 border bg-light text-center">Income/Expenses Bar Graph</div>
                    <div>
                        <canvas id="myChart"></canvas>
                    </div>
                </div>
                    @foreach (Goal goal in Model.Goals)
                    {
                        if (goal == Model.Goals.Last())
                        {
                            <div class="col">
                                <div class="p-3 border bg-light text-center">Current Goal</div>
                            <div class="p-3 border bg-light"><vc:goal-link name="@goal.Name">@goal.Name</vc:goal-link></div>
                            </div>
                        }
                    }

                </div>
                </div>
    <div class="container overflow-hidden" style="margin-top: 50px;">
        <div class="row gx-5">
                <div class="col">
                    <div class="p-3 border bg-light">Current Recurring Payments</div>
                    @foreach (RecurringPayment recur in Model.RecurringPayments)
                    {
                            DateTime now = DateTime.Now;
                            int intervalsPassed = (int)((now - recur.StartingDate).TotalDays / recur.PaymenFrequencyDays);
                            DateTime nextPaymentDate = recur.StartingDate.AddDays((intervalsPassed + 1) * recur.PaymenFrequencyDays);
                            TimeSpan timeUntilNextPayment = nextPaymentDate - now;


                        
                            <div class="p-3 border bg-light">Amount: @recur.PaymentAmount.ToString("C2")</div>
                            <div class="p-3 border bg-light">Frequency: @recur.PaymenFrequencyDays | Days Until next Payment @timeUntilNextPayment.Days</div>
                        
                    }
            </div>
            <div class="container overflow-hidden" style="margin-top: 50px;">
                <div class="row gx-5">
                    <div class="col">
                            <div class="p-3 border bg-light">Current Income Payments</div>
                            @foreach (Income income in Model.Income)
                            {
                                DateTime now = DateTime.Now;
                                int intervalsPassed = (int)((now - income.StartingDate).TotalDays / income.PayPeriodDays);
                                DateTime nextPaymentDate = income.StartingDate.AddDays((intervalsPassed + 1) * income.PayPeriodDays);
                                TimeSpan timeUntilNextPayment = nextPaymentDate - now;



                                <div class="p-3 border bg-light">Amount: @income.IncomeAmmount.ToString("C2")</div>
                                <div class="p-3 border bg-light">Frequency: @income.PayPeriodDays | Days Until next Payment @timeUntilNextPayment.Days</div>

                            }
                    </div>
                </div>
            </div>
            <div class="container overflow-hidden" style="margin-top: 50px;">
                <div class="row gx-5">
                    <div class="col">
                        <div class="p-3 border bg-light text-center">Contact Us for Finacial Advice
                            <div class="p-3 bg-light">
                                <a class="btn btn-primary" style="display: flex; justify-content: center;" asp-controller="Home"
                                     asp-action="Contact">
                                    Contact
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
}
@if (!signInManager.IsSignedIn(User))
{
}
else{
<script>
    const ctx = document.getElementById('myChart');
    @foreach (RecurringPayment transaction in Model.RecurringPayments)
    {
        totalExpenses = totalExpenses + transaction.PaymentAmount;
    }
    @foreach (Income income in Model.Income)
    {
        totalIncome = totalIncome + income.IncomeAmmount;
    }
    new Chart(ctx, {
        type: 'bar',
        data: {
            labels: ['Expenses', 'Income'],
            datasets: [{
                label: 'Income/Expenses',
                data: [@totalExpenses, @totalIncome],
                borderWidth: 1
            }]
        },
        options: {
            scales: {
                y: {
                    beginAtZero: true
                }
            }
        }
    });
</script>
}

BudgetWepApp/Views/Home/ThankYou.cshtml
<h1>Thank You for submiting a Contact form!</h1>
<div>
    <p>Thank you for taking the time to contact us. We will responded to you here shortly! For now please go to the home page and continue enjoying our budget application.</p>
</div>
<a class="btn btn-primary" asp-controller="Home" asp-action="Index">Home</a>